version: '3'

services:
  postgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
    volumes:
       - db_postgres:/var/lib/postgresql/data
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    networks:
      - ws_pocket
    restart: unless-stopped

networks:
  ws_pocket:
    driver: bridge

volumes:
    db_postgres: